apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: AssignMetadata
metadata:
  name: foo-label
spec:
  match:
    scope: Cluster
    kinds:
    - apiGroups: ["*"]
      kinds: ["Namespace"]
  location: "metadata.labels.foo"
  parameters:
    assign:
      value:  "qux"

