apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: AssignMetadata
metadata:
  name: foo-label
spec:
  applyTo:
  - groups: [""]
    kinds: ["Namespace"]
    versions: ["v1"]
  location: "metadata.labels.foo"
  parameters:
    assign:
      value:  "qux"
